package dev.samir.backend.common;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import dev.samir.backend.common.configuration.Environment;

/**
 * This class provides methods to generate unique identifiers and random numbers.
 * 
 * @author Scheide, Samir <samir.scheide@gmail.com>
 */
public final class RandomUtils implements GenerateRandom {
	
	/**
	 * 
	 */
	private static final Logger LOGGER = LoggerFactory.getLogger(RandomUtils.class);
	
	/**
	 * Generates a unique identifier. The identifier is generated by creating a random alphanumeric sequence.
	 * 
	 * @return a unique identifier containing only numbers and letters.
	 * @see {@link Environment#ENV_ID_LENGTH_CREATION}
	 */
	public final String randomUniqueIdentifier() {
		LOGGER.debug("Generating random sequence with length size of {}", getEnvironment().getIdLengthCreation());
		return GenerateRandom.super.alphaNumericSequence();
	}
	
}
